name: Red Urban
favicon: null
layout_spectrum: 0.6041277262847871
typography_spectrum: 0.35338859958574176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.45005557616241276
  lightness: 0.7292347494512796
  saturation: 0.3962169161532074
  rhythmicContrast: 0.1434887053910643
purpose: []
