name: Red Urban
favicon: null
layout_spectrum: 0.6041277262847871
typography_spectrum: 0.35338859958574176
title: Red Urban Amsterdam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f44335'
    - '#ff0000'
    - '#aa0000'
    - '#ff4924'
    - '#eb3b27'
  brandStrength: 0
  lightness: 0.7292347494512796
  saturation: 0.3962169161532074
  rhythmicContrast: 0.1434887053910643
purpose: []
